version: 2.1
orbs:
  jira: circleci/jira@1.1.2
jobs:
  build:
    docker:
      - image: cimg/openjdk:11.0.12
    steps:
      - checkout
      - run:
          command: mvn clean deploy -s .circleci/settings.xml
          name: Build and upload to Leaflet Internal repository
workflows:
  build:
    jobs:
      - build:
         context: leaflet_ci
         filters:
           branches:
             only:
               - master
         post-steps:
           - jira/notify:
               environment_type: production
               job_type: build
  version: 2.1